/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef asyncTest_CONSTANTS_H
#define asyncTest_CONSTANTS_H

#include "asyncTest_types.h"

namespace thrift { namespace example {

class asyncTestConstants {
 public:
  asyncTestConstants();

};

extern const asyncTestConstants g_asyncTest_constants;

}} // namespace

#endif
